package visao;


import Negocio.Aluno;
import javax.swing.JOptionPane;
import Modelo.LivroDAO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Matheus
 */
public class TelaCadastrarLivro extends javax.swing.JPanel {

    LivroDAO objVerificador = new LivroDAO();
    
    
    private PrincipalBiblioteca refEmprestimo;
    public TelaCadastrarLivro(PrincipalBiblioteca refEmprestimo) {
        initComponents();
        this.refEmprestimo = refEmprestimo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        campoAno = new javax.swing.JTextField();
        campoEditora = new javax.swing.JTextField();
        campoTitulo = new javax.swing.JTextField();
        campoAutor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        campoCategoria = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        campoPrateleira = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        campoInfo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Prateleira:");
        add(jLabel7);
        jLabel7.setBounds(90, 345, 62, 15);

        campoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAnoActionPerformed(evt);
            }
        });
        add(campoAno);
        campoAno.setBounds(150, 140, 100, 30);

        campoEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEditoraActionPerformed(evt);
            }
        });
        add(campoEditora);
        campoEditora.setBounds(150, 260, 240, 30);

        campoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloActionPerformed(evt);
            }
        });
        add(campoTitulo);
        campoTitulo.setBounds(150, 100, 350, 30);
        add(campoAutor);
        campoAutor.setBounds(150, 220, 350, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Titulo:");
        add(jLabel1);
        jLabel1.setBounds(89, 105, 50, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Ano:");
        add(jLabel2);
        jLabel2.setBounds(90, 145, 40, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tipo:");
        add(jLabel3);
        jLabel3.setBounds(90, 185, 40, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Autor:");
        add(jLabel4);
        jLabel4.setBounds(90, 225, 45, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Editora:");
        add(jLabel5);
        jLabel5.setBounds(90, 265, 48, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Categoria:");
        add(jLabel6);
        jLabel6.setBounds(90, 305, 70, 17);

        campoCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCategoriaActionPerformed(evt);
            }
        });
        add(campoCategoria);
        campoCategoria.setBounds(170, 300, 220, 30);

        campoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoActionPerformed(evt);
            }
        });
        add(campoTipo);
        campoTipo.setBounds(150, 180, 180, 30);

        campoPrateleira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPrateleiraActionPerformed(evt);
            }
        });
        add(campoPrateleira);
        campoPrateleira.setBounds(170, 340, 350, 30);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(190, 390, 100, 30);

        jButton2.setText("Cancelar");
        add(jButton2);
        jButton2.setBounds(420, 390, 110, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setText("Cadastro De Livro");
        add(jLabel9);
        jLabel9.setBounds(280, 50, 210, 30);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/livro1.png"))); // NOI18N
        add(jLabel14);
        jLabel14.setBounds(560, 130, 83, 84);

        jButton3.setText("Limpar");
        add(jButton3);
        jButton3.setBounds(300, 390, 110, 30);
        add(campoInfo);
        campoInfo.setBounds(540, 230, 120, 20);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Inter2.png"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(-20, 0, 790, 480);
    }// </editor-fold>//GEN-END:initComponents

    private void campoPrateleiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPrateleiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPrateleiraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            objVerificador.controleCadastroDeLivro(campoTitulo.getText(),Integer.parseInt(campoAno.getText()),
                    campoTipo.getText(),campoAutor.getText(), campoEditora.getText(), campoCategoria.getText(), campoPrateleira.getText());
       
                   
            if(objVerificador.getLivro() != null){
                campoInfo.setText("Livro cadastrado");
                
                //DEVERA SER CHAMADO UM METODO PARA IMPORTAR ALUNO E ESVAZIAR A VARIAVEL ATUAL 
                objVerificador.setLivro(null);
              //  limpaCampos();   
            }else{
                 
                campoInfo.setText("Dados Inválidos.");
            }
           
        }catch(NumberFormatException erro){
            JOptionPane.showMessageDialog(null,"Existe informações invalidas.","Dado invalido",
                    JOptionPane.ERROR_MESSAGE, null);
            campoInfo.setText("Dados Inválidos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    private void campoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAnoActionPerformed

    private void campoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoActionPerformed

    private void campoEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEditoraActionPerformed

    private void campoCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoAno;
    private javax.swing.JTextField campoAutor;
    private javax.swing.JTextField campoCategoria;
    private javax.swing.JTextField campoEditora;
    private javax.swing.JLabel campoInfo;
    private javax.swing.JTextField campoPrateleira;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
